run:
  tests: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - exportloopref
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - maligned
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - unparam
    - misspell
    - nolintlint

issues:
  exclude-rules:
    # Disables the naming linting (e.g. DbCoin should be DBCoin)
    - text: "ST1003:"
      linters:
        - stylecheck
  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  maligned:
    # Print struct with more effective memory layout or not, false by default
    suggest-new: true
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
