chain:
  bech32_prefix: desmos
  modules:
    - profiles

node:
  type: remote
  config:
    rpc:
      client_name: djuno
      address: http://65.21.152.138:26657
      max_connections: 10
    grpc:
      address: 65.21.152.138:9090
      insecure: true

parsing:
  workers: 5
  listen_new_blocks: true
  parse_old_blocks: true
  parse_genesis: false
  start_height: 2226900

database:
  name: morpheus-apollo-djuno
  host: 139.162.160.203
  port: 5432
  user: djuno
  password: goF7WENb0Uq4
  max_open_connections: 15
  max_idle_connections: 10

logging:
  level: info
  format: text

telemetry:
  port: 9090

pruning:
  keep_recent: 20
  keep_every: 720
  interval: 120