table:
  schema: public
  name: application_link
object_relationships:
  - name: profile
    using:
      foreign_key_constraint_on: user_address
  - name: score
    using:
      foreign_key_constraint_on:
        column: application_link_row_id
        table:
          schema: public
          name: application_link_score
array_relationships:
  - name: application_link_oracle_requests
    using:
      foreign_key_constraint_on:
        column: application_link_id
        table:
          schema: public
          name: application_link_oracle_request
select_permissions:
  - role: anonymous
    permission:
      columns:
        - application
        - creation_time
        - expiration_time
        - result
        - state
        - user_address
        - username
      filter: {}
      limit: 50
