table:
  schema: public
  name: application_link_oracle_request
object_relationships:
  - name: application_link
    using:
      foreign_key_constraint_on: application_link_id
select_permissions:
  - role: anonymous
    permission:
      columns:
        - id
        - application_link_id
        - request_id
        - script_id
        - call_data
        - client_id
        - height
      filter: {}
      allow_aggregations: true
