table:
  name: chain_link_chain_config
  schema: public
array_relationships:
  - name: chain_links
    using:
      foreign_key_constraint_on:
        column: chain_config_id
        table:
          name: chain_link
          schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - name
      filter: {}
      limit: 50
