table:
  schema: public
  name: application_link_oracle_request
select_permissions:
  - role: anonymous
    permission:
      columns:
        - call_data
        - client_id
        - request_id
        - script_id
      filter: {}
      limit: 50
