table:
  name: application_link_oracle_request
  schema: public
object_relationships:
  - name: application_link
    using:
      foreign_key_constraint_on: application_link_id
select_permissions:
  - role: anonymous
    permission:
      columns:
        - call_data
        - client_id
        - request_id
        - script_id
      filter: {}
      limit: 50
