table:
  schema: public
  name: application_link
object_relationships:
  - name: oracle_request
    using:
      manual_configuration:
        remote_table:
          schema: public
          name: application_link_oracle_request
        insertion_order: null
        column_mapping:
          id: application_link_id
  - name: profile
    using:
      foreign_key_constraint_on: user_address
  - name: score
    using:
      foreign_key_constraint_on:
        column: application_link_row_id
        table:
          schema: public
          name: application_link_score
select_permissions:
  - role: anonymous
    permission:
      columns:
        - application
        - creation_time
        - expiration_time
        - result
        - state
        - user_address
        - username
      filter: {}
      limit: 50
