-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE medias
(
    id          integer REFERENCES post (id) ON DELETE CASCADE ON UPDATE CASCADE PRIMARY KEY,
    post_medias post_media[]
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX medias_pkey ON medias (id int4_ops);
