-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE media
(
    id        SERIAL PRIMARY KEY,
    post_id   integer NOT NULL REFERENCES post (id) ON DELETE CASCADE ON UPDATE CASCADE,
    uri       text    NOT NULL,
    mime_type text    NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX media_pkey ON media (id int4_ops);
