-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE optional_data
(
    id    integer REFERENCES post (id) ON DELETE CASCADE ON UPDATE CASCADE PRIMARY KEY,
    key   text,
    value text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX optional_data_pkey ON optional_data (id int4_ops);
