-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE poll_answer
(
    id          SERIAL PRIMARY KEY,
    poll_id     integer NOT NULL REFERENCES poll (id) ON DELETE CASCADE ON UPDATE CASCADE,
    answer_id   integer NOT NULL,
    answer_text text    NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX poll_answer_pkey ON poll_answer (id int4_ops);
