-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE poll
(
    id                      SERIAL PRIMARY KEY,
    question                text                     NOT NULL,
    end_date                timestamp with time zone NOT NULL,
    open                    boolean                  NOT NULL,
    allows_multiple_answers boolean                  NOT NULL,
    allows_answer_edits     boolean                  NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX poll_pkey ON poll (id int4_ops);
