-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE poll_data
(
    id                      integer PRIMARY KEY REFERENCES post (id) ON DELETE CASCADE ON UPDATE CASCADE,
    question                text                        NOT NULL,
    provided_answers        poll_answer[]               NOT NULL,
    end_date                timestamp without time zone NOT NULL,
    open                    boolean                     NOT NULL,
    allows_multiple_answers boolean                     NOT NULL,
    allows_answer_edits     boolean                     NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX poll_data_pkey ON poll_data (id int4_ops);
