-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- post ----------------------------------------------

CREATE TABLE post (
    id integer PRIMARY KEY,
    parent_id integer NOT NULL,
    message text NOT NULL,
    created timestamp with time zone NOT NULL,
    last_edited timestamp with time zone NOT NULL,
    allows_comments boolean NOT NULL,
    subspace text NOT NULL,
    creator character varying(45) NOT NULL,
    poll_id integer REFERENCES poll(id) ON DELETE CASCADE ON UPDATE CASCADE,
    optional_data json
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX post_pkey ON post(id int4_ops);
