-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE post (
    id integer PRIMARY KEY,
    parent_id integer NOT NULL,
    message text NOT NULL,
    created timestamp without time zone NOT NULL,
    last_edited timestamp without time zone,
    allows_comments boolean NOT NULL,
    subspace text NOT NULL,
    creator character varying(40) UNIQUE
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX post_pkey ON post(id int4_ops);
CREATE UNIQUE INDEX post_creator_key ON post(creator text_ops);
