-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE reaction
(
    id      SERIAL PRIMARY KEY,
    post_id integer               NOT NULL REFERENCES post (id) ON DELETE CASCADE ON UPDATE CASCADE,
    owner   character varying(45) NOT NULL,
    val     text                  NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX reaction_pkey ON reaction (id int4_ops);
