-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE user_poll_answer
(
    id           SERIAL PRIMARY KEY,
    poll_id      integer               NOT NULL REFERENCES poll (id) ON DELETE CASCADE ON UPDATE CASCADE,
    answers      integer[]             NOT NULL,
    user_address character varying(45) NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_poll_answer_pkey ON user_poll_answer (id int4_ops);
